import os
from github import Github
from dotenv import load_dotenv

# Load environment variables
load_dotenv()
token = os.getenv("GITHUB_TOKEN")
if not token:
    raise ValueError("GITHUB_TOKEN is not set. Please add it to a .env file.")

# Initialize GitHub API
g = Github(token)

# Repository details
repo_name = "marsdialer/ubuntuvicidialer"  # Replace with your repo name
repo = g.get_repo(repo_name)

# File details
file_path = "bot_generated_file.txt"  # File to modify/create
content = "This content was generated by the bot."
commit_message = "Automated update via bot"

try:
    # Check if the file exists
    file = repo.get_contents(file_path)
    # Update the file
    repo.update_file(file.path, commit_message, content, file.sha)
    print(f"File updated: {file_path}")
except Exception as e:
    # If the file doesn't exist, create it
    repo.create_file(file_path, commit_message, content)
    print(f"File created: {file_path}")
